apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: veriff-app
  labels:
    app: words-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: words-db
  clusterIP: 10.96.0.100
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: veriff-app
  labels:
    app: words-db
spec:
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: db
        image: dockersamples/k8s-wordsmith-db
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: words
  namespace: veriff-app
  labels:
    app: words-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: words-api
  clusterIP: 10.96.0.101
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words
  namespace: veriff-app
  labels:
    app: words-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: words-api
    spec:
      containers:
      - name: words
        image: dockersamples/k8s-wordsmith-api
        ports:
        - containerPort: 8080
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: veriff-app
  labels:
    app: words-web
spec:
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30081
      name: web
  selector:
    app: words-web
  clusterIP: 10.96.0.107
  type: NodePort
  externalIPs: 206.189.170.172
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: veriff-app
  labels:
    app: words-web
spec:
  template:
    metadata:
      labels:
        app: words-web
    spec:
      containers:
      - name: web
        image: dockersamples/k8s-wordsmith-web
        ports:
        - containerPort: 80
          name: words-web
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
