apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    kubernetes.io/tls-acme: "true"
    #ingress.kubernetes.io/ssl-redirect: "true"
    #ingress.kubernetes.io/secure-backends: "true"
    #ingress.kubernetes.io/force-ssl-redirect: "true"
    #kubernetes.io/ingress.allow-http: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  name: app-wordsmith-ingress
  namespace: veriff-app
spec:
  tls:
  - hosts:
    - veriff.amandasouza.app
    secretName: veriff-tls
  rules:
    - host: veriff.amandasouza.app
    http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 8081

