apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth # secret name
    ingress.kubernetes.io/auth-realm: 'Authentication Required {{.ENVIRONMENT}}'
    certmanager.k8s.io/issuer: letsencrypt-staging
    ingress.kubernetes.io/secure-backends: "true"
    nginx.org/mergeable-ingress-type: "minion"
  name: app-wordsmith-ingress
  namespace: veriff-app
spec:
  rules:
  - host: veriff.amandasouza.app
    http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 8081

