apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: veriff
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
  name: app-wordsmith-ingress
  namespace: veriff-app
  labels:
    app.kubernetes.io/part-of: ingress-nginx
spec:
  rules:
          #- host: veriff.amandasouza.app
  - http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80

