kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  annotations:
    ingress.kubernetes.io/enable-modsecurity:   "true"
    ingress.kubernetes.io/enable-owasp-core-rules:  "true"
    ingress.kubernetes.io/modsecurity-snippet: |
        SecDebugLog /tmp/modsec_debug.log;
        SecRequestBodyAccess On;
        SecAuditLogParts ABCIJDEFHZ;
        SecAuditEngine RelevantOnly;
        Include "/etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf";
        Include "/etc/nginx/modsecurity/modsecurity.config";
    #DDoS Attacks
    ingress.kubernetes.io/limit-connections: 10
    ingress.kubernetes.io/limit-rps: 1

  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  #WAF Opened
  enable-modsecurity: "true"
  #WAF Rules
  enable-owasp-modsecurity-crs: "true"
  main-template: |
        load_module modules/ngx_http_modsecurity_module.so;
        user  nginx;
